import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Contact from "@/components/Contact";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1> Lista de Contactos </h1>
        <div className={styles.grid}>
          <Contact name="Juan Perez" email="juan@mail.com" phone="123456" />
          <Contact name="Juan Perez" email="juan@mail.com" phone="123456" />
          <Contact name="Juan Perez" email="juan@mail.com" phone="123456" />
          <Contact name="Juan Perez" email="juan@mail.com" phone="123456" />
          <Contact name="Juan Perez" email="juan@mail.com" phone="123456" />
        </div>
      </main>
    </>
  );
}
